#!/bin/bash
set -euo pipefail

# Input parameter
SOURCE=${1:-}
TARGET=${2:-}

# Check inputs: must pass at least two parameters
if [[ -z "$SOURCE" ]] || [[ -z "$TARGET" ]]; then
    echo "Usage: deliver [source] [target]"
    exit 1
fi

# Exit if anything has pending changes
if [[ -n $(git status -uno --porcelain) ]]; then
    echo "You have pending changes, commit or stash first"
    exit 2
fi

git fetch
git checkout $SOURCE
git rebase origin/$SOURCE
git checkout $TARGET
git rebase origin/$TARGET
git merge $SOURCE
git push origin $SOURCE
git push --atomic origin $SOURCE $TARGET
git checkout $SOURCE
