#!/bin/bash

# Exit script on (almost) all errors
# instead of continuing silently
set -euo pipefail

# Input parameter
PROJECT=${1:-}
SERVER=${2:-01}

# Print the usage instructions
function print_usage {
    echo "Usage: deploy_production [username] [server]"
    echo "Valid servers are 01 and 02. Optional, default 01"
    exit 1
}

# Function that runs on the server
function update_code {
    cd www

    if [ -f artisan ]; then
        php artisan down
        php artisan clear-compiled
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
    fi

    git checkout master
    git pull --ff-only origin master

    if [ -f composer.lock ]; then
        composer install --no-interaction --prefer-dist --optimize-autoloader
    fi

    if [ -f artisan ]; then
        php artisan up
    fi

    exit
}

# Check inputs: must pass at least one parameter
if [[ -z "$PROJECT" ]]; then
    print_usage
fi

# Login to the server, copy all functions to it, and run the update function
ssh $PROJECT@in10-web-p$SERVER.sc.nines.nl "$(typeset -f); update_code"

echo "Done"
