#!/usr/bin/ruby

require 'yaml'

# Usage information if no parameters are passed
name = ARGV[0]
abort "Usage: vagrant_provision [name]" unless name

# Check the homestead file exists
path = ENV['HOME'] + '/homestead/'
configFile = "#{path}Homestead.yaml"
if File.exist? configFile then
    settings = YAML::load(File.read(configFile))
else
    abort "#{configFile} not found or not readable"
end

# Check for previous deployment
if settings['databases'].include? name
    abort "Project #{name} has been created previously"
end

# Add settings
settings['databases'] << name
settings['sites'] << {
    'map' => "#{name}.lcl",
    'to' => "/home/vagrant/code/#{name}/public",
}

# Write updated settings and reprovision vagrant configuration
File.write(configFile, settings.to_yaml)
puts "Updated settings"
puts "Reloading vagrant configuration"
`(cd #{path}; vagrant reload --provision)`

# Open browser
`open http://#{name}.lcl`
puts "All done"
